//Route Planner, V1.0

/*
This function takes the route table generated by tradePlanner and chains the route legs together, consumes the trades, and runs the trade planner again to select the next legs
*/

import { buildTradeLeg } from "./buildTradeLeg.js";

export function routePlannerV1(data, options) {
    const {
        startExchange,
        maxCapital,
        shipTonnage,
        shipVolume,
        fuelCost,
        maintCost,
        minProfit,
        maxLegs,
        sortBy
    } = options;

    const workingData = {
        ...data,
        orderBooks: structuredClone(data.orderBooks)
    };

    let legCount = 0;
    const plannedRoute = [];

    let currentCapital = maxCapital;
    let currentExchange = startExchange;

    while (legCount < maxLegs) {
        const leg = buildTradeLeg(workingData, {
            buyExchange: currentExchange,
            maxCapital: currentCapital,
            shipTonnage,
            shipVolume,
            fuelCost,
            maintCost,
            minProfit,
            sortBy: sortBy ?? "TripNetProfit"
        });

        if (!leg) {
            break;
        }

        const plannedLeg = {
            Leg: legCount + 1,
            StartingCapital: Number(currentCapital.toFixed(2)),
            EndingCapital: Number((currentCapital + leg.NetProfit).toFixed(2)),
            ...leg
        };

        plannedRoute.push(plannedLeg);

        currentCapital += leg.NetProfit;
        currentExchange = leg.SellExchange;
        legCount++;
    }

    const totalProfit = plannedRoute.reduce(
        (sum, leg) => sum + leg.NetProfit,
        0
    );

    return {
        StartExchange: startExchange,
        EndingExchange: currentExchange,
        StartingCapital: maxCapital,
        EndingCapital: Number(currentCapital.toFixed(2)),
        TotalProfit: Number(totalProfit.toFixed(2)),
        Legs: plannedRoute
    };
}